import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/navbar";
import { RiTimerFlashFill } from "react-icons/ri";
import { IoIosHappy } from "react-icons/io";
import { MdFreeBreakfast} from "react-icons/md"
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Thereswift</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-poppins">
        <Navbar />
        <div className="bg-main h-screen flex justify-center items-center ">
          <div className="container flex justify-between">
            <div className="w-[40%] mr-10">
              <h1 className="text-6xl font-bold mb-10 ">
                Meds <br /> Made Simple.
              </h1>
              <h1 className="text-lg mb-10">
                Theraswift Rx is the pharmacy that provides your lowest
                prescription price, keep track of your refill plus free same day
                delivery - all from your phone
              </h1>
              <div className="flex items-center text-lg font-medium mb-10">
                <h1 className="flex mr-5 items-center ">
                  <span className="mr-2 text-2xl">
                    <RiTimerFlashFill />{" "}
                  </span>
                  Save time
                </h1>
                <h1 className="flex mr-5 items-center ">
                  <span className="mr-2 text-2xl">
                    <MdFreeBreakfast />{" "}
                  </span>
                  Stress free
                </h1>
                <h1 className="flex mr-5 items-center ">
                  <span className="mr-2 text-2xl">
                    <IoIosHappy />{" "}
                  </span>
                  Be happy
                </h1>
              </div>
              <button className="bg-white font-bold text-base rounded-lg px-7 py-4">
                {" "}
                Get Started
              </button>
            </div>
            <div className="w-[60%]">
              <img
                src="/heroImage.png"
                alt="logo"
                // width={200}
                // height={70}
                className="w-full"
              />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
